- name: "Run load testing"
  hosts: remotevms
  serial: '{{ LOCUST_SERIAL }}'
  vars:
    LOCUST_TARGET: data-vm # siibra-api, siibra-explorer
    LOCUST_USERS: "1"
    LOCUST_RUNTIME: "600s" # max runtime
    LOCUST_SERIAL: "1"

  tasks:
  - name: Enable locust and run load test
    shell: |
      export LOCUST_TARGET="{{ LOCUST_TARGET }}"
      cd siibra-infrastructure-profiling \
        && . venv/bin/activate \
        && locust --host https://atlases.ebrains.eu \
          --headless \
          --run-time {{ LOCUST_RUNTIME }} \
          --users {{ LOCUST_USERS }} \
          --csv locust_output/output \
          --json-file locust_output/output \
          --skip-log \
          --exit-code-on-error 0 \
          -f conf/locustfile.py

    become: false
    args:
      executable: /bin/bash
    changed_when: false
